// Run with: npx ts-node --esm scripts/seed-products.ts
// Or add to package.json: "seed": "ts-node --esm scripts/seed-products.ts"

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || "https://lunmbxlngkebuaiblwwm.supabase.co";
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || "";

interface Product {
  name: string;
  price: number;
  description: string;
  category: string;
  images: string[];
  stock: number;
  strength?: string;
  size?: string;
  flavor?: string;
  is_active: boolean;
}

const allProducts: Product[] = [
  // ============ WINES ============
  {
    name: "Prosecco",
    price: 9.99,
    description: "Italian sparkling wine, light and refreshing with fine bubbles",
    category: "Wines",
    images: ["/Images/Wines/Prosecco.jpeg"],
    stock: 50,
    size: "750ml",
    is_active: true,
  },
  {
    name: "Canti Prosecco",
    price: 11.99,
    description: "Premium Italian Prosecco with elegant bubbles and fruity notes",
    category: "Wines",
    images: ["/Images/Wines/Canti Prosecco.jpeg"],
    stock: 40,
    size: "750ml",
    is_active: true,
  },
  {
    name: "Isla Negra",
    price: 7.99,
    description: "Chilean wine with rich flavors and smooth finish",
    category: "Wines",
    images: ["/Images/Wines/Isla Negra.png"],
    stock: 60,
    size: "750ml",
    is_active: true,
  },
  {
    name: "Chardonnay",
    price: 8.99,
    description: "Classic white wine with buttery notes and crisp finish",
    category: "Wines",
    images: ["/Images/Wines/Chardonnay.jpeg"],
    stock: 55,
    size: "750ml",
    is_active: true,
  },
  {
    name: "Chardonnay Rich & Smooth",
    price: 10.99,
    description: "Premium Chardonnay with rich, smooth texture and oak undertones",
    category: "Wines",
    images: ["/Images/Wines/Chardonnay Rich and smooth.jpeg"],
    stock: 35,
    size: "750ml",
    is_active: true,
  },
  {
    name: "Pinot Grigio",
    price: 8.49,
    description: "Light and crisp Italian white wine with citrus notes",
    category: "Wines",
    images: ["/Images/Wines/Pinot Grigio.jpeg"],
    stock: 45,
    size: "750ml",
    is_active: true,
  },
  {
    name: "Sauvignon Blanc",
    price: 9.49,
    description: "Fresh and zesty white wine with tropical fruit flavors",
    category: "Wines",
    images: ["/Images/Wines/Sauvignon Blanc.jpeg"],
    stock: 50,
    size: "750ml",
    is_active: true,
  },
  {
    name: "High Tide",
    price: 7.49,
    description: "Easy-drinking wine perfect for any occasion",
    category: "Wines",
    images: ["/Images/Wines/High tide.png"],
    stock: 60,
    size: "750ml",
    is_active: true,
  },
  {
    name: "Villa Maria",
    price: 12.99,
    description: "New Zealand premium wine with exceptional quality",
    category: "Wines",
    images: ["/Images/Wines/Villa Maria.jpeg"],
    stock: 30,
    size: "750ml",
    is_active: true,
  },
  {
    name: "Oyster Bay Sauvignon Blanc",
    price: 13.99,
    description: "Premium New Zealand Sauvignon Blanc with intense flavors",
    category: "Wines",
    images: ["/Images/Wines/Sauvignon Blanc Oyster bay.jpeg"],
    stock: 25,
    size: "750ml",
    is_active: true,
  },
  {
    name: "Jacob's Creek",
    price: 8.99,
    description: "Australian wine with balanced flavors and smooth finish",
    category: "Wines",
    images: ["/Images/Wines/Jacob's Creek.jpg"],
    stock: 55,
    size: "750ml",
    is_active: true,
  },

  // ============ SPIRITS ============
  {
    name: "Smirnoff Red Label Vodka",
    price: 16.99,
    description: "Classic triple-distilled vodka, smooth and versatile",
    category: "Spirits",
    images: ["/Images/Spirits/Smirnoff Red label.jpeg"],
    stock: 40,
    strength: "37.5%",
    size: "700ml",
    is_active: true,
  },
  {
    name: "Gordon's Pink Gin",
    price: 18.99,
    description: "Pink gin infused with raspberries, strawberries and redcurrant",
    category: "Spirits",
    images: ["/Images/Spirits/Gordon's dry gin pink edition.png"],
    stock: 35,
    strength: "37.5%",
    size: "700ml",
    is_active: true,
  },
  {
    name: "Captain Morgan Original Spiced Gold",
    price: 19.99,
    description: "Caribbean rum blended with secret spices and natural flavors",
    category: "Spirits",
    images: ["/Images/Spirits/Captain morgan Original special gold.jpeg"],
    stock: 30,
    strength: "35%",
    size: "700ml",
    is_active: true,
  },
  {
    name: "Appleton Estate 21 Year Old",
    price: 89.99,
    description: "Premium aged Jamaican rum with rich, complex flavors",
    category: "Spirits",
    images: ["/Images/Spirits/Appleton estate 21 years old nassau valley casks.jpeg"],
    stock: 10,
    strength: "43%",
    size: "700ml",
    is_active: true,
  },
  {
    name: "Buffalo Trace Bourbon",
    price: 27.99,
    description: "Kentucky straight bourbon with notes of vanilla, toffee and candied fruit",
    category: "Spirits",
    images: ["/Images/Spirits/Buffalo trace bourbon.jpeg"],
    stock: 25,
    strength: "40%",
    size: "700ml",
    is_active: true,
  },
  {
    name: "Chivas Regal",
    price: 32.99,
    description: "Premium blended Scotch whisky with rich, smooth taste",
    category: "Spirits",
    images: ["/Images/Spirits/Chivas legal.jpg"],
    stock: 20,
    strength: "40%",
    size: "700ml",
    is_active: true,
  },

  // ============ READY MIXED DRINKS ============
  {
    name: "Gordon's Gin & Tonic",
    price: 2.49,
    description: "Pre-mixed Gordon's gin with tonic water, refreshing and ready to drink",
    category: "Ready Mixed Drinks",
    images: ["/Images/Soft Drinks/Gordon's Gin & tonic.png"],
    stock: 100,
    strength: "5%",
    size: "250ml",
    is_active: true,
  },
  {
    name: "Gordon's Gin & Diet Tonic",
    price: 2.49,
    description: "Gordon's gin with diet tonic, lower calories same great taste",
    category: "Ready Mixed Drinks",
    images: ["/Images/Soft Drinks/Gordon's Gin & diet tonic.jpeg"],
    stock: 80,
    strength: "5%",
    size: "250ml",
    is_active: true,
  },
  {
    name: "Vodka & Cranberry",
    price: 2.29,
    description: "Smooth vodka mixed with sweet cranberry juice",
    category: "Ready Mixed Drinks",
    images: ["/Images/Soft Drinks/Vodka & Cranberry.jpeg"],
    stock: 90,
    strength: "5%",
    size: "250ml",
    is_active: true,
  },
  {
    name: "Vodka & Cola",
    price: 2.29,
    description: "Classic vodka and cola combination, ready to enjoy",
    category: "Ready Mixed Drinks",
    images: ["/Images/Soft Drinks/Vodka & cola.jpeg"],
    stock: 95,
    strength: "5%",
    size: "250ml",
    is_active: true,
  },

  // ============ SOFT DRINKS ============
  {
    name: "Pepsi Max",
    price: 1.49,
    description: "Maximum taste, zero sugar cola",
    category: "Soft Drinks",
    images: ["/Images/Soft Drinks/Pepsi Max.png"],
    stock: 200,
    size: "500ml",
    is_active: true,
  },

  // ============ VAPES & E-LIQUIDS ============
  {
    name: "Caliburn G2 Carbon Black",
    price: 24.99,
    description: "Sleek pod vape system with adjustable airflow and long battery life",
    category: "Vapes & E-Liquids",
    images: ["/Images/Vapes & E-Liquids/Caliburn-g2-carbon-black.jpg"],
    stock: 30,
    is_active: true,
  },
  {
    name: "Elf Bar Raya D2",
    price: 12.99,
    description: "Disposable vape with rich flavors and 600 puffs",
    category: "Vapes & E-Liquids",
    images: ["/Images/Vapes & E-Liquids/Elf-bar-raya-d2.webp"],
    stock: 50,
    is_active: true,
  },
  {
    name: "Geek Bar Pulse Disposable",
    price: 14.99,
    description: "High-capacity disposable vape with intense flavor",
    category: "Vapes & E-Liquids",
    images: ["/Images/Vapes & E-Liquids/Geek-bar-pulse-disposable.webp"],
    stock: 45,
    is_active: true,
  },
  {
    name: "Cherry Cola E-Liquid",
    price: 5.99,
    description: "Sweet cherry cola flavored e-liquid",
    category: "Vapes & E-Liquids",
    images: ["/Images/Vapes & E-Liquids/Cherry Cola.webp"],
    stock: 60,
    strength: "20mg",
    size: "10ml",
    flavor: "Cherry Cola",
    is_active: true,
  },
  {
    name: "Canada Blueberry Raspberry",
    price: 5.99,
    description: "Mixed berry flavor with blueberry and raspberry notes",
    category: "Vapes & E-Liquids",
    images: ["/Images/Vapes & E-Liquids/Canada-blueberry-raspberry.webp"],
    stock: 55,
    strength: "20mg",
    size: "10ml",
    flavor: "Berry",
    is_active: true,
  },
  {
    name: "Fruit Bomb E-Liquid 130ml",
    price: 19.99,
    description: "Large bottle fruit mix e-liquid, perfect for all-day vaping",
    category: "Vapes & E-Liquids",
    images: ["/Images/Vapes & E-Liquids/fruit-bomb2-130ml-30mg.webp"],
    stock: 25,
    strength: "30mg",
    size: "130ml",
    flavor: "Fruit Mix",
    is_active: true,
  },
  {
    name: "Tokyo Iced Peach",
    price: 8.99,
    description: "Refreshing iced peach flavor from Japan",
    category: "Vapes & E-Liquids",
    images: ["/Images/Vapes & E-Liquids/Tokyo-Iced-Peach-30ml.webp"],
    stock: 40,
    strength: "30mg",
    size: "30ml",
    flavor: "Iced Peach",
    is_active: true,
  },
  {
    name: "Blue Razz Ice",
    price: 5.99,
    description: "Blue raspberry with cool menthol finish",
    category: "Vapes & E-Liquids",
    images: ["/Images/Vapes & E-Liquids/Blue razz ice.jpg"],
    stock: 70,
    strength: "20mg",
    size: "10ml",
    flavor: "Blue Raspberry",
    is_active: true,
  },
  {
    name: "Cherry Ice",
    price: 5.99,
    description: "Sweet cherry with icy menthol kick",
    category: "Vapes & E-Liquids",
    images: ["/Images/Vapes & E-Liquids/Cherry ice.jpg"],
    stock: 65,
    strength: "20mg",
    size: "10ml",
    flavor: "Cherry",
    is_active: true,
  },
  {
    name: "Cherry Ice & Lemon Ice Combo",
    price: 9.99,
    description: "Duo pack of cherry ice and lemon ice flavors",
    category: "Vapes & E-Liquids",
    images: ["/Images/Vapes & E-Liquids/Cherry ice & Lemon ice.jpg"],
    stock: 40,
    strength: "20mg",
    size: "2x10ml",
    flavor: "Cherry & Lemon",
    is_active: true,
  },
  {
    name: "Double Apple",
    price: 5.99,
    description: "Classic double apple shisha-style flavor",
    category: "Vapes & E-Liquids",
    images: ["/Images/Vapes & E-Liquids/Double apple.jpg"],
    stock: 55,
    strength: "20mg",
    size: "10ml",
    flavor: "Double Apple",
    is_active: true,
  },
  {
    name: "Dubai Chocolate",
    price: 6.99,
    description: "Rich chocolate dessert flavor",
    category: "Vapes & E-Liquids",
    images: ["/Images/Vapes & E-Liquids/Dubai chocolate.jpg"],
    stock: 45,
    strength: "20mg",
    size: "10ml",
    flavor: "Chocolate",
    is_active: true,
  },
  {
    name: "Grapefruit Passion Fruit",
    price: 5.99,
    description: "Tropical blend of grapefruit and passion fruit",
    category: "Vapes & E-Liquids",
    images: ["/Images/Vapes & E-Liquids/Grapefruit passion fruit.jpg"],
    stock: 50,
    strength: "20mg",
    size: "10ml",
    flavor: "Tropical",
    is_active: true,
  },
  {
    name: "Pineapple Ice",
    price: 5.99,
    description: "Sweet pineapple with cooling menthol",
    category: "Vapes & E-Liquids",
    images: ["/Images/Vapes & E-Liquids/Pineapple ice.jpg"],
    stock: 60,
    strength: "20mg",
    size: "10ml",
    flavor: "Pineapple",
    is_active: true,
  },
  {
    name: "Strawberry Kiwi",
    price: 5.99,
    description: "Fresh strawberry and kiwi fruit blend",
    category: "Vapes & E-Liquids",
    images: ["/Images/Vapes & E-Liquids/Strawberry kiwi.jpg"],
    stock: 55,
    strength: "20mg",
    size: "10ml",
    flavor: "Strawberry Kiwi",
    is_active: true,
  },
  {
    name: "Banana Ice",
    price: 5.99,
    description: "Creamy banana with cool ice finish",
    category: "Vapes & E-Liquids",
    images: ["/Images/Vapes & E-Liquids/Banana ice.jpg"],
    stock: 50,
    strength: "20mg",
    size: "10ml",
    flavor: "Banana",
    is_active: true,
  },
  {
    name: "Blackberry Ice",
    price: 5.99,
    description: "Sweet blackberry with icy menthol",
    category: "Vapes & E-Liquids",
    images: ["/Images/Vapes & E-Liquids/Blackberry ice.jpg"],
    stock: 45,
    strength: "20mg",
    size: "10ml",
    flavor: "Blackberry",
    is_active: true,
  },
  {
    name: "Blueberry Cherry Cranberry",
    price: 6.49,
    description: "Triple berry mix with blueberry, cherry and cranberry",
    category: "Vapes & E-Liquids",
    images: ["/Images/Vapes & E-Liquids/Blueberry cherry cranberry.jpg"],
    stock: 40,
    strength: "20mg",
    size: "10ml",
    flavor: "Mixed Berry",
    is_active: true,
  },

  // ============ SWEETS ============
  {
    name: "Mixed Candy Selection",
    price: 2.99,
    description: "Assorted candy mix perfect for sharing",
    category: "Sweets",
    images: ["/Images/Sweets/pexels-pixabay-33239.jpg"],
    stock: 100,
    is_active: true,
  },
  {
    name: "Gummy Bears",
    price: 1.99,
    description: "Classic gummy bear sweets in assorted flavors",
    category: "Sweets",
    images: ["/Images/Sweets/pexels-koshi-887853.jpg"],
    stock: 120,
    is_active: true,
  },
  {
    name: "Chocolate Truffles",
    price: 4.99,
    description: "Premium chocolate truffles, perfect gift",
    category: "Sweets",
    images: ["/Images/Sweets/pexels-polina-tankilevitch-5469044.jpg"],
    stock: 50,
    is_active: true,
  },
  {
    name: "Jelly Beans",
    price: 2.49,
    description: "Colorful jelly beans in multiple flavors",
    category: "Sweets",
    images: ["/Images/Sweets/pexels-pixabay-65882.jpg"],
    stock: 90,
    is_active: true,
  },
  {
    name: "Lollipops Assorted",
    price: 0.99,
    description: "Assorted fruit flavor lollipops",
    category: "Sweets",
    images: ["/Images/Sweets/pexels-daniblaj95-6007945.jpg"],
    stock: 150,
    is_active: true,
  },

  // ============ BEERS & CIDERS ============
  {
    name: "Craft Lager",
    price: 3.49,
    description: "Premium craft lager, crisp and refreshing",
    category: "Beers & Ciders",
    images: ["/Images/Beers & Cider's/pexels-thatguycraig000-1634074.jpg"],
    stock: 80,
    strength: "4.5%",
    size: "330ml",
    is_active: true,
  },
  {
    name: "IPA Ale",
    price: 3.99,
    description: "India Pale Ale with hoppy bitterness and citrus notes",
    category: "Beers & Ciders",
    images: ["/Images/Beers & Cider's/pexels-grzegorz-2777274-5402366.jpg"],
    stock: 60,
    strength: "5.5%",
    size: "330ml",
    is_active: true,
  },
  {
    name: "Premium Lager 4-Pack",
    price: 7.99,
    description: "Four pack of premium lager beers",
    category: "Beers & Ciders",
    images: ["/Images/Beers & Cider's/pexels-introspectivedsgn-9646272.jpg"],
    stock: 45,
    strength: "4.8%",
    size: "4x330ml",
    is_active: true,
  },
  {
    name: "Apple Cider",
    price: 3.29,
    description: "Crisp apple cider, naturally refreshing",
    category: "Beers & Ciders",
    images: ["/Images/Beers & Cider's/pexels-ron-martinez-2313692-4044674.jpg"],
    stock: 70,
    strength: "4.5%",
    size: "500ml",
    is_active: true,
  },
  {
    name: "Craft Beer Selection",
    price: 12.99,
    description: "Mixed selection of craft beers",
    category: "Beers & Ciders",
    images: ["/Images/Beers & Cider's/pexels-brettjordan-25311376.jpg"],
    stock: 30,
    strength: "Various",
    size: "4x330ml",
    is_active: true,
  },
];

async function seedProducts() {
  console.log(`Seeding ${allProducts.length} products...`);

  for (const product of allProducts) {
    try {
      const response = await fetch("http://localhost:3000/api/products", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(product),
      });

      if (response.ok) {
        console.log(`✓ Added: ${product.name}`);
      } else {
        const error = await response.json();
        console.log(`✗ Failed: ${product.name} - ${error.error}`);
      }
    } catch (err) {
      console.log(`✗ Error: ${product.name} - ${err}`);
    }
  }

  console.log("\nSeeding complete!");
}

seedProducts();
